### ISSUE TITLE
extend tinyMQTT to handle 256 byte MQTT data

### ISSUE THREAD

**Issue by MaBecker** [olliephillips/tinyMQTT#11]
Hi Ollie, 

need to send large mqtt data than 127, so started reading docs and digging into tinyMQTT.js

Found this on [Understanding the MQTT Protocol](http://www.steves-internet-guide.com/mqtt-protocol-messages-overview/)

>The minimum size of the packet length field is 1 byte which is for messages with a total length less than 127 bytes.(not including control and length fields).
>
>The maximum packet size is 256MB. Small packets less than 127 bytes have a 1 byte packet length field.

That means if  2. byte is larger than 127 a different approach is need to split topic and message from data. Piercing the code with console.log and adding a var called var_ofs did it. This is the workig result.  

```
function onDat(data) {
    var cmd = data.charCodeAt(0);
    console.log('cmd:',cmd, cmd >> 4 );
    if((cmd >> 4) === 3) {
        console.log('data: ['+data+']');
        console.log('0-4: ',data.charCodeAt(0),data.charCodeAt(1),data.charCodeAt(2),data.charCodeAt(4));
        var var_len = data.charCodeAt(1) > 127 ? data.charCodeAt(4) : data.charCodeAt(2) << 8 | data.charCodeAt(3);
        var var_ofs = data.charCodeAt(1) > 127 ? 5 : 4 ; 
        console.log('topic:   offset:',var_ofs,'length:',var_len);
        console.log('message: offset:',var_ofs+var_len,'length:',(data.charCodeAt(1))-var_len);
        var msg = {
                topic: data.substr(var_ofs, var_len),
		message: data.substr(var_ofs+var_len, (data.charCodeAt(1))-var_len)
        };
        _q.emit('message', msg);
    }
}
```
Created no pull request, because not sure if you like the style of fix.

Used MQTTBox and this Payload

    {"c":"b","d": { "t": [ {"x":0,"y":0,"s":25,"t":"HS820"},{"x":0,"y":30,"s":25,"t":"FSTC"}],"a":8,"b":12,"c":40,"d":44}}'
 
    topic : espruino/MaBe/C1120B, messageId : , length : 142

As tinyMQTT is a copy in parts of Espruino [MQTT.js](http://www.espruino.com/modules/MQTT.js) will have to inform Gordon too :)

**Comment by olliephillips** [comment]
I don't know @MaBecker, I'm sure there are some var optimisations but without the logging statements it looks like it would add 200 bytes to library as is. Given tiny was always the goal here, and I wonder how often people do need to send more than 127 bytes and whether it is worth the increase in size given this?  Not averse to adding it in just my initial thoughts.

**Comment by MaBecker** [comment]
Ok with me, added changes to my fork. 

Yes 200 bytes more, use if and else and shorten data.charCodeAt would be a way to save some bytes.

**Comment by olliephillips** [comment]
I think that's the best way to go for now Mark, I think I maybe I cling to "tiny" when it's not so relevant now, but otherwise what is this library? Hope you are well.

**Comment by MaBecker** [comment]
Well, with some small change and using minify.js it is even smaller, check the lates[ commit](https://github.com/MaBecker/tinyMQTT/commit/2534397ad623e0c1eb41cd69ad36057a7e945a91)
