### ISSUE TITLE
Syntax error when requiring online library

### ISSUE THREAD

**Issue by aliustaoglu** [olliephillips/tinyMQTT#12]
I am working with ESP8266 12-E with 4 MB. I can connect to Wifi and ping it. But when I include this library from github using the address I get below Syntax error caused by the library. If I remove the require bit it runs fine.

Here's my code:

```javascript
E.on('init', function() {
  var WIFI_NAME = 'SPARK';
  var WIFI_OPTIONS = { password: 'XXXXX' };

  var wifi = require('Wifi');
  wifi.connect(
    WIFI_NAME,
    WIFI_OPTIONS,
    function(err) {
      console.log('Connected!');
      // If I remove below it connects to Wifi and I can ping it normally
      var mqtt = require("https://github.com/olliephillips/tinyMQTT/blob/master/tinyMQTT.min.js");
    }
  );
});


```

And here's the screen output:

```sh
--] 
--] >
--]  ____                 _ 
--] |  __|___ ___ ___ _ _|_|___ ___ 
--] |  __|_ -| . |  _| | | |   | . |
--] |____|___|  _|_| |___|_|_|_|___|
--]          |_| espruino.com
--]  1v99 (c) 2018 G.Williams
--] 
--] Espruino is Open Source. Our work is supported
--] only by sales of official boards and donations:
--] http://espruino.com/Donate
--] Flash map 4MB:512/512, manuf 0xc8 chip 0x4016
--] 
--] >Uncaught SyntaxError: Got EOF expected '}'
--]  at line 4 col 1
--] 
--] ^
--] >
--] Compacting Flash...
--] Calculating Size...
--] Writing..
```

Any ideas? I am not using WebIDE. I am using espruino npm package to upload my code:

```sh
espruino -p /dev/cu.wchusbserial1420 -b 115200 --board boards/ESP8266_4MB.json -e 'save()' index.js
```

**Comment by olliephillips** [comment]
Hello. I've no Espruino gear to hand to be able to test with at the moment. Could you try the unminified version - it may fit as the jsvars in the ESP8266 version have increased quite a bit - and me know. I'll be able to test tomorrow when I have access to ESP8266 again.

**Comment by aliustaoglu** [comment]
I think you're right. It works with IDE. 

Weird it works with IDE but not with the espruino library. I thought IDE was using the library in the background. I'll try to take a look at the IDE source code to see how it uploads the code. 

So it's not library related issue. We can close this. Thanks for the support.
