### ISSUE TITLE
Cool new version - even smaller 

### ISSUE THREAD

**Issue by MaBecker** [olliephillips/tinyMQTT#13]
> but I'm only publishing.

* Is there a reason why you use different types of quotation marks 
* loading from storage needs  "\\x00"

Will start the tests over the weekend and use this issue for any findings and feedback.

**Comment by olliephillips** [comment]
On the quotation marks question, no.  There have been some merged pull requests so might be personal preference creeping in, I wouldn't check for that.  But it's as likely to be down to me, I don't know.

**Comment by MaBecker** [comment]
Will add some more actions by tomorrow like

- disconnect every 15 min and reconnect 
- reboot every 57min

any other things in you mind that should be tested?

**Comment by olliephillips** [comment]
Nothing to add that's more sophisticated than I've run before. I can see them publishing, and will check in on them from time to time.

**Comment by MaBecker** [comment]
> just moving the _q = this assignment up the function so more this keywords can be removed.

good point, makes it easier to read.

The qoute things has no effect it is just a question of style. Was reading this [stuff](https://github.com/moderndeveloper-students/Modern-Developer-JavaScript-Style-Guide) and the quote section.

**Comment by MaBecker** [comment]
The other qoute things is that '\x00' will not work if this module ist placed in storage, it causes a syntax error. It has to be changed to '\\x00'

This is how to store a module and use it with require. Only variable part are created in ram rest is processed from storage (flash)  

```
// save_tinyMQTT_to_storage.js
s = require('Storage');
// replace `<....>`with tinyMQTT.min.js 
s.write('tinyMQTTS', `<.....>`);
````
 
````
// test_tinyMQTT_from_storage
mqtt = require('tinyMQTTS');
// that's it
````

**Comment by MaBecker** [comment]
Devices-Test is now running with this [code](https://gist.github.com/MaBecker/3a8d184c1702b3f9a05991347b4b0e36)

**Comment by MaBecker** [comment]
Maybe it would be nice to setup [crouton](https://crouton.mybluemix.net/crouton/gettingStarted) to this visible ;-)

**Comment by olliephillips** [comment]
Not come across that. Will have a look.

**Comment by MaBecker** [comment]
passed first reboot ;-) works great.

**Comment by olliephillips** [comment]
> passed first reboot ;-) works great.

Great news! 

That include to storage code above is cool, I hadn't considered saving modules there 

> is that '\x00' will not work if this module ist placed in storage, it causes a syntax error. It has to be changed to '\x00'

You'll have to clarify - the two values look the same. What needs to be changed?

**Comment by MaBecker** [comment]
> You'll have to clarify - the two values look the same. What needs to be changed?

take a look this [issue](https://github.com/espruino/Espruino/issues/1583#issuecomment-446502124)

**Comment by MaBecker** [comment]
> Re save to storage - is that freeing memory/jsvars over a typical sketch upload and `save()`. If so typically how many? More room for application code?

Yes and Yes. Only some vars get loaded in ram most parts just directly run from storage.
Check the output of `global`

I upload a oled module, tinyMQTT and one of the [new fonts](http://forum.espruino.com/comments/14531235/)  to the storage to save lots of memory/jvars.

**Comment by MaBecker** [comment]
No problem, works perfect! 

Will stop the test when back home ;-)

Did you had time to test tinyMQTT from storage? 
Do you need some more input?

**Comment by olliephillips** [comment]
Great news, thanks so much for your efforts on that test suite. If it has run on that for over a week then that's a huge comfort, should be robust enough fairly complex pub/sub. 

Re that issue on storage you directed me to. I did look, but honestly, I didn't quite follow it.  If you want to make a PR that makes the change, or just spell it out to me, I'm happy to amend!

**Comment by MaBecker** [comment]
just added a PR

**Comment by MaBecker** [comment]
>is that '\x00' will not work if this module ist placed in storage, it causes a syntax error. It has to be changed to '\x00'

Oh, I can see the second back slash got lost ...

**Comment by olliephillips** [comment]
Ah that makes sense. I wondered what I was looking at

**Comment by olliephillips** [comment]
Merged that PR. Going to close this now. Thanks again.
