### ISSUE TITLE
How to store tinyMQTT in Storage to save vars and heap

### ISSUE THREAD

**Issue by MaBecker** [olliephillips/tinyMQTT#16]
save to Storage 

```
s = require('Storage');

s.write('tinyMQTT',"......put tinyMQTT.min.js here.........");
```

use direct from Storage

```
> mqtt = require('tinyMQTT');    
={
  create: function (a,b) { ... }
 }
> global
={
  s: function () { [native code] },
  Error: function () { [native code] },
  String: function () { [native code] },
  mqtt: {
    create: function (a,b) { ... }
   }
 }

```

**Comment by olliephillips** [comment]
I will add this to the README as a tip or something. That ok with you?

**Comment by olliephillips** [comment]
I've added it above the credits section. Let me know if I missed anything. Will close this one. Thanks @MaBecker

**Comment by olliephillips** [comment]
Lets' use this issue @MaBecker for any further discussion on the storage piece :)

**Comment by olliephillips** [comment]
Reference this https://github.com/olliephillips/tinyMQTT/issues/20#issuecomment-471624712

**Comment by MaBecker** [comment]
\\\x00 fo sFCC(0) in 

https://github.com/MaBecker/tinyMQTT/blob/master/tinyMQTT.js#L87

https://github.com/MaBecker/tinyMQTT/blob/master/tinyMQTT.js#L124

**Comment by MaBecker** [comment]
build store_tinyMQTT.js  from tinyMQTT.min.js with a few simple Unix commands 

```
echo -n "require('Storage').write('tMQTT','" > x
echo -n "');" > y
cat x tinyMQTT.min.js y > store_tinyMQTT.js
rm x y 
```

**Comment by olliephillips** [comment]
Nice approach using ```SFCC(0)```.  Added this and you get a mention in the commit. README updated. Closing now
