### ISSUE TITLE
Publish length "self-defense"

### ISSUE THREAD

**Issue by AkosLukacs** [olliephillips/tinyMQTT#17]
Hi!

First, thanks for your work! And I just started messing with mqtt, so maybe these limitations are obvious for someone more experienced...

Although the documentation clearly states that there is a 127 byte publishing limit, the library does not check the length. Accidentally went over the length limit, and started getting `disconnected` messages. I had no idea why my code isn't working. Also, that (or maybe me trying to reconnect) causes memory leak, and eventually a crash. In my case it was 71 vars / iteration, but that number probably depends on the surrounding code.

I think the length limit is for the `topic + data`, right? At first I thought it's just the data...

I know this library is meant to be tiny, but maybe add a length check in `publish`? Should I send a pull request?

**Comment by olliephillips** [comment]
Hi there! Though I've never hit the publish limit myself and haven't seen this behaviour, I can see how, a generic disconnect message would be confusing and unhelpful in debugging. A PR which catches this and prevents the disconnect or just refines the error is definitely worth having and would be appreciated if you have the time to address. Thank you!

**Comment by olliephillips** [comment]
Merged.
