### ISSUE TITLE
Publishing Issue

### ISSUE THREAD

**Issue by olliephillips** [olliephillips/tinyMQTT#19]
Anything newer than commit e12acb98aa6c70c82bbe8f50f0e931c8c3cbe5a4 now seems unreliable when publishing. It seems to stop after 30 or so publications.  On Espruino it appears to be fine. The subscribers just stop reporting. Replicated on a remote and local broker.

**Comment by MaBecker** [comment]
can confirm that.

**Comment by olliephillips** [comment]
My testing would suggest it is the double escaping (for the purpose of the loading from storage) which is causing the problem, though I know not why. Remove it from the next latest commit which ceases at 31 messages, and publishing is long term again.  Are you able to verify?

**Comment by olliephillips** [comment]
I've removed the escaping for now @MaBecker. It did seem to be causing this. Have you not encountered anything like this? To replicate use the module directly (not from storage) with the escaping in and watch the subscription cease. Then remove the escaping, and run again. Subscriptions continue indefinitely again. At least this is the behaviour I see.

**Comment by MaBecker** [comment]
Using escaping in load from storage works but fails for native usage.
This is a serious issue Gordon should be informed about

**Comment by olliephillips** [comment]
In the context of tinyMQTT, it obviously loads the module and commences operation as normal, but something happens shortly in, though`process.memory()` on Espruino gives nothing away, and the program appears to be publishing as normal.  Have you come across before?

**Comment by MaBecker** [comment]
reopened https://github.com/espruino/Espruino/issues/1583
