### ISSUE TITLE
require without create is missing connect

### ISSUE THREAD

**Issue by MaBecker** [olliephillips/tinyMQTT#24]
just wanted to let you know about this.

Used this two cases 

```
function test_case_A() { 
  var mqtt = require("https://github.com/olliephillips/tinyMQTT/blob/master/tinyMQTT.min.js");
  mqtt.create("test.mosquitto.org");
  mqtt.connect();

}

function test_case_B() { 
  var mqtt = require("https://github.com/olliephillips/tinyMQTT/blob/master/tinyMQTT.min.js").create("test.mosquitto.org");
  mqtt.connect();
}
```

output  for case A and B
 
```
>test_case_A();
Uncaught Error: Function "connect" not found!
 at line 3 col 8
  mqtt.connect();
       ^
in function "test_case_A" called from line 1 col 13
test_case_A();
            ^
>test_case_B();
=undefined
> 
```

**Comment by olliephillips** [comment]
Hi @MaBecker, thanks. I think ```connect``` was unexported some time ago when trying to add back authentication which was deemed a must have in the Espruino Gitter discussions. It was "low hanging fruit" so to speak,  removed to maintain size.

```require``` without ```create``` does return a function on which ```connect``` can be called. 

This has never been an issue for me, though it has one or two others ( I recall at least one issue). That said, a valid "connect" approach is documented, and not unprecedented when initialising a module. Open to suggestions of course.

**Comment by MaBecker** [comment]
Not issue at all, just wanted to name that I hit that pitfall.

It was the first time  I tried to use mqtt like in case A. 

It is just about the documentation in section https://github.com/olliephillips/tinyMQTT#how-to-use

maybe just replace 

`var mqtt = require("tinyMQTT");` 

with 

`var mqtt = require("tinyMQTT").create("<your mqtt broker>");`

Just to avoid case A and fall into that trap ;-)

Fell free to close.

**Comment by olliephillips** [comment]
Ok, absolutely yes, that's my error when I recently amended the README, you're absolutely correct @MaBecker the way it is there will definitely cause more people to hit this. I will update it ASAP  - thanks!

**Comment by MaBecker** [comment]
Are you still on gitter?

**Comment by olliephillips** [comment]
I am but I don't tend to use very often
