### ISSUE TITLE
keep_alive 65535 fix + last will support

### ISSUE THREAD

**Issue by jejdacz** [olliephillips/tinyMQTT#27]
I've made fix on hardcoded keep_alive option 255, 255 in mqCon(), and support for Last will feature.

**Comment by olliephillips** [comment]
Hello, thanks for opening up the discussion on this. Do you have more details on the motivation for these features and the impact on library size?

As you've probably guessed this a bare-bones module that makes no secret that it implements only the bare essentials of the MQTT spec in the interests of being as small as possible, but if these are features we need to have then I'm very happy to have the discussion. 

Interesting that you've implemented last will feature. I don't think that is in some of the more full featured libraries even. How are you using this? My approach is generally to attempt to reconnect on a disconnect event, so communincation hopefully resumes. What do your clients do when they receive the last will message?  Thanks again.

**Comment by jejdacz** [comment]
Hi, 
I'm building an garden watering application. 
One tinyMQTT client is on ESP-12 that controls valve and has some sensors connected. It is powered by battery.
Another MQTT client (let's call it Controller) handles watering logic and serves web application. It runs on Node.js on Raspberry.
Broker runs on Raspberry.

I need a way to tell Controller when ESP suddenly stops working, due malfunctions e.g. empty battery. Because it won't be able to send disconnect packet and even reconnect in these scenarios.
So, Controller receive the last will of ESP when keep_alive timeout and updates app state.

Truth is that disconnect message could be published by the Broker when the client's keep_alive timeout. But It seems an unnecessary hack to me.

I'm just a beginner, maybe I'm doing that wrong.

Minified file is about 70Bytes larger.

**Comment by gfwilliams** [comment]
The main Espruino MQTT lib doesn't have it as far as I know. It sounds like a great thing to add though.

Having it in the main MQTT lib is a no-brainer IMO. Up to you whether you think it should go in the tiny version :)

**Comment by olliephillips** [comment]
Last will feature was picked up in another PR, based on your code @jejdacz. That has been merged, so I am closing this. I note there are some additional items in your fork @jejdacz re keep alive and binary number notation? If you'd like for those pieces to be included please open a separate issue and we can have the discussion there. Thanks for this issue, your code example which formed some of that PR, and thanks for the input @gfwilliams

**Comment by atmosuwiryo** [comment]
I'm using LWT to notify when the device has been "badly" disconnected. On normal disconnection, the broker discards the stored LWT message. 

I'm confidence with the device status with the LWT feature, event if the device failed to reconnect to the mqtt broker.

Ref: https://www.hivemq.com/blog/mqtt-essentials-part-9-last-will-and-testament/
