### ISSUE TITLE
LWT

### ISSUE THREAD

**Issue by iammikecohen** [olliephillips/tinyMQTT#31]
Hello,
I see that you implemented LWT. I'm having trouble adding LWT to my app and am seeking assistance. I pass the will_topic and will_payload to the create method.
When I unplug the device I'm hoping to see the LWT message triggered but it does not. My MQTT broker is Mosquitto and the client is an ESP8266 running Espruino. Any advice would be greatly appreciated.

```
mqtt.create(address, {
      username,
      password,
      port,
      will_topic: opts.will_topic,
      will_payload: opts.will_payload
    });
```

**Comment by olliephillips** [comment]
Hey @iammikecohen  I actually haven't used this feature myself, it was community submitted. I might have some time this week to set up an ESP8266 and test. If I can I can help I'll post here.

cc: @jejdacz (no requirement to jump in here of course, but if you can spare the time, appreciated)

**Comment by iammikecohen** [comment]
Ok, I'll gladly submit to the readme if I figure it out. It's not my highest priority but, I'm hoping to get my devices conforming to the Homie convention which requires a working LWT.

**Comment by jejdacz** [comment]
I think you gonna need to set "keep_alive" parameter, because it's default value is 65535 seconds.
Here is my code tested with "aedes" broker:

const mqtt = require("tinyMQTT-mod").create("10.0.0.200",{
    client_id : "random",    
    keep_alive: 10,
  username:"john",
  password:"secret",
    will_topic: "esp/disconnected",
    will_payload: JSON.stringify({msg:"exit"})
});

**Comment by jejdacz** [comment]
I've just tested tinyMQTT on ESP8266 with aedes mqtt broker on PC. It works.
It's necessary to use the latest tinyMQTT module version.

ESP8266 code:
const mqtt = require("https://github.com/olliephillips/tinyMQTT/blob/master/tinyMQTT.js").create("10.0.0.200",{       
    keep_alive: 10,  
    will_topic: "esp/disconnected",
    will_payload: JSON.stringify({msg:"exit"})
}); 

NOTE:
In tinyMQTT module is default "keep_alive" parameter 60 seconds.
The broker must disconnect a client that does not send a a message or a PINGREQ packet in one and a half times the keep alive interval.

**Comment by olliephillips** [comment]
@jejdacz Hey that's terrific thanks for taking the time. That's a good point re the latest tinyMQTT - @iammikecohen use this repo. The module on the espruino site does not have this feature - I need to update it, my fault, just not got to it. Hope that helps. Going to close this. Hopefully all good. Thanks again Marek :)

**Comment by iammikecohen** [comment]
Thanks y’all. Using the latest from this repo instead of the Espruino module fixed everything. 

Thanks for the feature @jejdacz; it works great.

**Comment by jejdacz** [comment]
Happy to hear that.
