### ISSUE TITLE
Package.json

### ISSUE THREAD

**Issue by iammikecohen** [olliephillips/tinyMQTT#32]
Would you accept a pull request or be willing to add a package.json file?

I would like to manage this as a dependency through npm.

**Comment by olliephillips** [comment]
Hi. Thanks for checking. I’ve no problem at all with this. If you want to create the PR I should be able to merge it without delay.

**Comment by iammikecohen** [comment]
https://github.com/olliephillips/tinyMQTT/pull/33

**Comment by olliephillips** [comment]
Merged #33. Added your name to the credits. Just let me know on that versioning point?

**Comment by iammikecohen** [comment]
re: Versioning, I used the default Semantic Versioning value that `npm init` suggested. You may want to go back and add some tags on the history to refer to older releases. It will be helpful going forward to know when LWT support was added or a default value changed.

**Comment by olliephillips** [comment]
No releases to date. The file won’t impact how Espruino users are using it. I’ll update the file as we move forward with this repo.
