### ISSUE TITLE
empty message if message is to long

### ISSUE THREAD

**Issue by MaBecker** [olliephillips/tinyMQTT#5]
Hi Ollie,

no idea if this is a tinyMQTT or a Espruino issue - starting with tinyMQTT :)

````
// board: ESP8266 

var mqtt = require('tinyMQTT').create('192.168.0.103');

var myid = '02f184',
    controller = 'bbb10';

mqtt.on('connected', function(){
   console.log("connected");
  mqtt.subscribe(controller+'/'+myid);
});

mqtt.on("message", function(msg){
  console.log('topic:',msg.topic);
  console.log('message:',msg.message);
});

setTimeout(function(){mqtt.connect();},1000);
````

Message:

````
0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
````

Output:

````
connected
topic: bbb10/02f1840123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
message:
````

double checked with MQTTBox

![bildschirmfoto 2017-03-12 um 10 26 17](https://cloud.githubusercontent.com/assets/15932646/23830570/6e53fb12-070e-11e7-8a0a-99c356490da6.JPG)

**Comment by olliephillips** [comment]
Interesting, TBH only tested with much smaller payloads. I'll have a look at this maybe later but certainly early this week. Payload length is 144 there, have you found a threshold below which you get good return? Doe chars make a difference. What if alpha chars only rather than numeric? If you get chance to try while you are set up might help narrow it down

**Comment by MaBecker** [comment]
a payload (topic+message) of 127 chars is the limit

**Comment by olliephillips** [comment]
Too much coincidence. 128 byte limit? I'll bet this is also the case in the core MQTT library, and the library on which that was based. I'll have a look though. How many bytes are you wanting to send?

**Comment by MaBecker** [comment]
> Too much coincidence. 128 byte limit?

![bildschirmfoto 2017-03-12 um 12 41 24](https://cloud.githubusercontent.com/assets/15932646/23831428/478dcd6a-0721-11e7-8012-4c501b45bba5.JPG)

one byte more and it is broken :)

Only wanted to mention that there is a limit. I am fine with 127 byte in total.

**Comment by olliephillips** [comment]
No problem, interested to know the limitations. Looking into it to it there is a publish limit of 128 bytes, this would appear to be in many of the Node libraries too.  Go longer and the client disconnects. Implement extra code relating to remaining length and it is possible to send more. It would make the library a fair bit bigger though - and given what data is likely to be published via tinyMQTT 127, as you say, is probably plenty.

But you are subscribing not publishing with tinyMQTT, and in my test on the iot.eclipse.org I could send more than 128 chars and have tinyMQTT subscribe and read it fine. Remaining length has to be implemented by the publishing client, to determine in advance how big the payload is, and communicate it, so maybe a try another MQTT client for publishing if you purely want to subscribe on ESP8266 - I'm testing using MQTTLens to publish to the topic my ESP8266 is subscribed to.

I'll make a note in the README about the 127 char publishing limit though.
