### ISSUE TITLE
Add an option for reconnect interval

### ISSUE THREAD

**Issue by wanglingsong** [olliephillips/tinyMQTT#6]
As title, Can you add one more config option for the reconnect interval?

**Comment by olliephillips** [comment]
So you'd use the `disconnect` event listener, call `mqtt.connect()` again, but want to adjust the reconnect attempt interval, downwards presumably?

**Comment by wanglingsong** [comment]
I want to adjust the reconnect attempt interval. I saw it is hardcoded as 2 second.

**Comment by olliephillips** [comment]
I wonder about the scenario where connection is not possible and reconnection attempts are being made. We don't have many sockets available in ESP8266, so you could see connection attempts backing up and ESP8226 running out of sockets? 2 seconds was chosen to allow the connection attempt process to complete and socket to close. It was an arbitrary selection in all honesty though.

I'm not averse to it being configurable, but if you wanted to change for your use-case maybe in first instance, fork the repo and change it there. Then your `require` statement simply becomes the path to your repo. Alternatively, if you download and use from Espruino Web IDE, you can change the code locally.

If all goes well please feed back.

**Comment by wanglingsong** [comment]
My objective is to reduce the energy consumption of esp8266. Reconnecting in every 2 sec is too frequent for my application. If my MQTT brocker is down, I don't want my esp8266 keep running for reconnecting. It may be busier than it was connected. Anyway, I can fork it and do it myself. Thanks for your kindly advice.

**Comment by olliephillips** [comment]
Thinking about this, what you propose makes a lot of sense. Sorry I got the wrong end of the stick - thinking you wanted to bring the interval down. If you do this in your fork in a way that is accessible via config object rather than hardcoded would love to have a PR ;)

**Comment by olliephillips** [comment]
Closed by 72a0c30
