### ISSUE TITLE
Customized client id

### ISSUE THREAD

**Issue by wanglingsong** [olliephillips/tinyMQTT#9]
Is it possible to let user to define the client id?
I looked at the source. Currently, getSerial() is used.
```
		_q.cl.write(mqCon(getSerial()));
```

**Comment by olliephillips** [comment]
This was a convenience as it can be relied upon to be unique while keeping the code footprint small, but yes you could substitute it and would have to, if not using on espruino. Hope that helps.

**Comment by wanglingsong** [comment]
I think I have to do it in my fork. Thanks!
